//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safina_422.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int ID_participant { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public int Phone { get; set; }
        public string GameStatistics { get; set; }
        public string RoleInTeam { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
