//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safina_422.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standing
    {
        public int ID_standing { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> NumberMatches { get; set; }
        public string ParticipantStatus { get; set; }
    }
}
