//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safina_422.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int ID_statistic { get; set; }
        public int ColMatchesPlayed { get; set; }
        public int ColWins { get; set; }
        public int ColDefeats { get; set; }
        public string PlaceTournament { get; set; }
        public string IndividualAchievements { get; set; }
    }
}
