//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safina_422.Components.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public int ID_tournament { get; set; }
        public string NameTournament { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Game { get; set; }
        public string Formats { get; set; }
        public int NumberParticipants { get; set; }
        public Nullable<decimal> PrizePool { get; set; }
        public string Status { get; set; }
        public string MinGameRank { get; set; }
        public string RegionalRestrictions { get; set; }
        public string ProhibitedCharactersWeapons { get; set; }
    }
}
